os: osx
before_install:
  - brew install ripgrep tidy-html5 vim --with-custom-python
  - npm install -g jsxhint eslint
jobs:
  - ruby install.rb
  - mkdir autoload
  - vim +PlugInstall
notifications:
  email: false
