language: ruby
os: osx
before_install:
  - brew bundle
  - npm install -g jsxhint eslint
script:
  - mkdir ~/.vim
  - ruby install.rb
  - cd ~/.vim
  - mkdir autoload
  - vim +PlugInstall
branches:
  only:
    - master
notifications:
  email: false
